credits={}
credits.people=[]
credits.guides=[]
credits.sounds=[]
credits.people.push("Joe Strout")
credits.people.push("BibleClinger")
credits.people.push("Redspark")
credits.guides.push("https://miniscript.org/wiki/Main_Page")
credits.guides.push("https://miniscript.org/books/index.html")
credits.guides.push("https://miniscript.org/MiniMicro/index.html#learn")
credits.guides.push("https://miniscript.org/files/MiniScript-Manual.pdf")
credits.sounds.push("https://pixabay.com/music/video-games-356-8-bit-chiptune-game-music-357518/")